### ISSUE TITLE
Can't build latest code using cake

### ISSUE THREAD

**Issue by kyegupov** [sstephenson/eco#3]
Something seems to be wrong with Cakefile.
That's what I get:

```
rainman@grand-piano ~/opensource/eco $ ~/bin/cake dist

fs:153
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: ENOENT, No such file or directory '/home/rainman/opensource/eco//home/rainman/opensource/eco/package.json'
    at Object.openSync (fs:153:18)
    at Object.readFileSync (fs:94:15)
    at /home/rainman/opensource/eco/Cakefile:44:17
    at Object.action (/home/rainman/opensource/eco/Cakefile:49:26)
    at /home/rainman/.node_libraries/.npm/coffee-script/0.9.5/package/lib/cake.js:31:26
    at /home/rainman/.node_libraries/.npm/coffee-script/0.9.5/package/lib/cake.js:53:23
    at path:81:19
    at node.js:773:9
```

**Comment by sstephenson** [comment]
What version of node are you using?

**Comment by kyegupov** [comment]
node version doesn't matter, the error is obvious.
See in Cakefile:

```
read = (filename) ->
    fs.readFileSync "#{__dirname}/#{filename}", "utf-8"
...
version = JSON.parse(read "#{__dirname}/package.json").version
```

path is prepended twice

**Comment by sstephenson** [comment]
My mistake. Thanks for pointing this out. (I think `__dirname` used to evaluate to `"."` in a previous version of CoffeeScript.)

Fixed in master.
